<div class="inner-container">
    <div class="row mt-4">
        <div class="col-md-7">
            <form class="general-form" method="post" action="<?php echo getFullUrl(true)?>">
                <div class="form-group">
                    <label><?php _l('to-leave-empty')?></label>
                    <select name="val[to][]" multiple data-url="user/search" class=" input-tags-fetch">
                        <?php if(isset($user) and $user):?>
                            <option value="<?php echo $user['id']?>" selected><?php echo $user['full_name']?></option>
                        <?php endif?>
                    </select>
                </div>

                <div class="form-group">
                    <label><?php _l('email-subject')?></label>
                    <input type="text" name="val[subject]" class="form-control"/>
                </div>

                <div class="form-group">
                    <label><?php _l('email-content')?></label>
                    <textarea name="val[text]" class="form-control rich-editor" id="newpage" rows="10"></textarea>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary round-sm"><?php _l('send')?></button>
                </div>
            </form>
        </div>
    </div>
</div>