<div class="payment-methods">

    <?php if(config('stripe-secret-key', '') != ''):?>

        <?php
            $currency = model('user')->getUserCurrency();
            if (!userCurrencySupportStripe()) {
                $price = convertBackToBase($price);
                $currency = config('currency-converter-source', 'USD');
            }
        ?>
        <div class="each">
            <a data-price="<?php echo $price?>"
               data-type="<?php echo $type?>"
               data-typeid="<?php echo $typeId?>"
               data-desc="<?php _l($detail['desc'])?>"
               data-title="<?php _l($detail['title'])?>"
               data-currency="<?php echo $currency?>"
               href="" id="stripeButton"><img src="<?php echo assetUrl('assets/images/stripe-btn.png')?>"/> </a>
        </div>
    <?php endif?>

    <?php if(config('paypal-username', '') != ''):?>
        <div class="each">
            <a href="<?php echo url('payment/paypal', array('type' => $type, 'typeid' => $typeId, 'price' => $price))?>"><img style="width: 197px;position:relative;left: -3px;" src="<?php echo assetUrl('assets/images/paypal-btn.png')?>"/> </a>
        </div>
    <?php endif?>



    <?php if(config('mollie-api-key', '')):?>
        <div class="each">
            <a href="<?php echo url('payment/mollie', array('type' => $type, 'typeid' => $typeId, 'price' => $price))?>"><img src="<?php echo assetUrl('assets/images/mollie.png')?>"/> </a>
        </div>
    <?php endif?>

    <?php if(config('enable-bank-transfer', false)):?>
        <script>
            function openBankTransfer(type,typeId,price) {
                $('#paymentMethodModal').modal('hide');
                $('#transfer-price').val(price);
                $('#transfer-type').val(type);
                $('#transfer-typeid').val(typeId);
                $("#bankTransferModal").modal('show');
                return false;
            }
        </script>
        <div class="each">
            <button onclick="return openBankTransfer('<?php echo $type?>','<?php echo $typeId?>', '<?php echo $price?>')" class="btn btn-block btn-lg  mt-2 round-sm" style="width:200px;background-image: radial-gradient( circle farthest-corner at 10% 20%,  rgba(242,106,81,1) 99.3%, rgba(187,187,187,1) 100.2% );margin: auto;font-weight: bold;color:#fff"><img style="width:20px" src="<?php echo assetUrl('assets/images/bank.png')?>"/> <?php _l('bank-transfer')?> </button>
        </div>
        <hr/>
    <?php endif?>
    <?php Hook::getInstance()->fire('payment.method', null, array($price,$type,$typeId,$detail))?>
</div>