<div class="grid playlist-container-<?php echo $playlist['id']?>">
    <?php
    $user = $C->model('user')->getUser($playlist['userid']);
    $track = $C->model('track')->getPlaylistFirstTrack($playlist['id']);
    ?>
    <div class="playlist-url-<?php echo $playlist['id']?>" data-link="<?php echo model('track')->playlistUrl($playlist)?>"></div>

    <div class="art track-hover-display-container" id="each-playlist-grid-<?php echo $playlist['id']?>" style="background-image: url(<?php echo $C->model('track')->getPlaylistArt($playlist, $user,$track, 600);?>)">
        <div class="play-container track-hover-display">
            <a href=""
               data-id="<?php echo $track['id']?>"
               data-art="<?php echo $C->model('track')->getArt($track)?>"
               data-title="<?php echo str_limit( $track['title'], 50)?>"
               data-link="<?php echo url('track/'.$track['id'])?>"
               data-owner="<?php echo $user['full_name']?>"
               data-owner-link="<?php echo $C->model('user')->profileUrl($user)?>"
               data-wave="<?php echo $track['wave'] ?>"
               data-type="playlist"
               data-typeid="<?php echo  $playlist['id']?>"
               data-wave-colored="<?php echo $track['wave_colored'] ?>"
               class="play-button track-play-button track-play-button-<?php echo $track['id']?>" id="track-play-button-<?php echo $track['id']?>" ><i class="fa  fa-play"></i></a>
            <div class="play-controls" data-wave="">
            </div>

            <div class="track-stats clearfix">
                <div class="float-left">
                    <?php $countLikes = $C->model('track')->countLikes('playlist', $playlist['id'])?>
                    <a href="" class="like-count-playlist-<?php echo $playlist['id']?>" style="<?php echo ($countLikes < 1) ? 'display:none': null?>"><i class="la la-heart-o"></i> <span><?php echo $countLikes?></span></a>

                </div>
                <div class="float-right">
                    <?php $hasLike = $C->model('track')->hasLiked('playlist', $playlist['id'])?>
                    <button data-toggle="tooltip" title="<?php echo ($hasLike) ? l('unlike') : l('like')?>" class=" btn like-button-playlist-<?php echo $playlist['id']?> ajax-action <?php echo ($hasLike) ? 'liked' : null?>" href="<?php echo url('like/item', array('type' => 'playlist', 'type_id' => $playlist['id']))?>"><i class="la la-heart"></i></button>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-title-container">
        <a href="<?php echo $C->model('track')->playlistUrl($playlist)?>" data-ajax="true" ><h1 class="grid-title"><b><?php echo format_output_text($playlist['name'])?></b></h1></a>
        <span class="grid-info">
            <?php if(!isset($noTrackCount)):?>
                <?php echo $C->model('track')->countPlaylistTracks($playlist['id'])?> <?php _l('tracks')?> |
            <?php endif?>
            <a href="<?php echo $C->model('user')->profileUrl($user)?>" data-ajax="true">
                <?php echo format_output_text($user['full_name'])?>
                <?php echo $C->view('user/badge', array('userid'=> $user['id']))?>
            </a></span>
    </div>
</div>