<?php if(model('user')->isAuthor($user) and (config('use-spotlight', 'all-author') == 'all-author' or model('user')->subscriptionActive($user['id']))):$tracks = model('spotlight::spotlight')->getTracks($user['id'])?>
    <?php if(count($tracks) > 0 or ($C->model('user')->isLoggedIn() and $C->model('user')->authId== $user['id'])):?>
        <div class="spotlight-container">

                <div class="clearfix">
                    <div class="float-left">
                        <h5><?php _l('spotlight')?>
                            <?php if($C->model('user')->isLoggedIn() and $C->model('user')->authId== $user['id']):?>
                                (<?php echo model('spotlight::spotlight')->countTracks()?>/<?php echo config('max-spotlight-tracks', 5)?>)
                            <?php endif?>
                        </h5>
                    </div>
                    <div class="float-right">
                        <?php if($C->model('user')->isLoggedIn() and $C->model('user')->authId== $user['id']):?>
                                <?php if(model('spotlight::spotlight')->canSpotlight()):?>
                                <button data-toggle="modal" data-target="#editSpotlightModal" class="btn btn-sm btn-secondary round-sm"><?php _l('edit-spotlight')?></button>
                            <?php else:?>
                                <button  class="btn btn-sm btn-secondary round-sm mtitle disabled" title="<?php _l('become-pro-edit-spotlight')?>"><?php _l('edit-spotlight')?></button>
                            <?php endif?>

                        <?php endif?>
                    </div>
                </div>

            <?php if($C->model('user')->isLoggedIn() and $C->model('user')->authId== $user['id'] and model('spotlight::spotlight')->canSpotlight()):?>
                <div class="modal" id="editSpotlightModal" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <form action="<?php echo url('spotlight/save')?>" method="post" class="general-form">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"><?php _l('edit-spotlight')?></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label><?php _l('select-track-playlist-album')?></label>
                                        <select name="val[tracks][]" multiple data-url="track/tags" class="spotlighttrackinput input-tags-fetch">
                                        </select>
                                    </div>
                                    <button type="submit" type="submit" id="spotlightavebutton" data-size="s" data-style="zoom-in" class="ladda-button btn btn-primary round-sm"><?php _l('add')?></button>
                                    <hr/>

                                    <div class="spotlight-edit-tracks">

                                        <?php echo view('spotlight::profile/edit-list')?>
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
                <?php endif?>



            <?php $tracks = model('track')->getTracks('my-spotlight', $user['id'],0, 5); echo view('track/lists', array('tracks' => $tracks, 'type' => 'my-spotlight', 'typeId' => $user['id'],'offset' => 0, 'viewType' => 'track'))?>
        </div>

        <h6 class="mt-3"><?php _l('recent')?></h6>
        <hr/>
        <?php endif?>
<?php endif?>
