
<?php
    $user = $C->model('user')->getUser($track['userid']);
    $title = $track['title'];
    $link = model('track')->trackUrl($track);
    $price = $track['price'];
    $buyType = 'track';
    $buyId = $track['id'];

    if (isset($track['playlist_id'])) {
        $playlist = model('track')->findPlaylist($track['playlist_id']);
        $title = $playlist['name'];
        $link = model('track')->playlistUrl($playlist);
        $price = $playlist['price'];
        $user = model('user')->getUser($playlist['userid']);
        $buyType = 'album';
        $buyId = $playlist['id'];
    }
?>
<div class="each grid each-track-<?php echo $track['id']?> track-<?php echo $track['id']?>" id="track-<?php echo $track['id']?>">
    <?php if(isset($track['playlist_id'])):?>
        <div class="playlist-url-<?php echo $playlist['id']?>" data-link="<?php echo model('track')->playlistUrl($playlist)?>"></div>
    <?php endif?>
    <div class="art track-hover-display-container" style="background-image: url(<?php echo model('track')->getArt($track);?>)">
        <div class="play-container track-hover-display">
            <a href=""
               data-id="<?php echo $track['id']?>"
               data-art="<?php echo $C->model('track')->getArt($track)?>"
               data-title="<?php echo str_limit( $track['title'], 50)?>"
               data-link="<?php echo url('track/'.$track['id'])?>"
               data-owner="<?php echo $user['full_name']?>"
               data-owner-link="<?php echo $C->model('user')->profileUrl($user)?>"
               data-wave="<?php echo $track['wave'] ?>"
               data-type="<?php echo $type?>"
               data-typeid="<?php echo $typeId?>"
               data-wave-colored="<?php echo $track['wave_colored'] ?>"
               class="play-button track-play-button track-play-button-<?php echo $track['id']?>" id="track-play-button-<?php echo $track['id']?>" ><i class="fa  fa-play"></i></a>
            <div class="play-controls" data-wave="">
            </div>
        </div>
    </div>
    <div class="info">
        <button  onclick="return buy_item('<?php echo $buyType?>','<?php echo $buyId?>')" class="btn btn-sm btn-outline-secondary btn-block grid-buy-button"><span class="colored"><strong><?php echo formatMoney($price)?></strong> <?php _l('buy-now')?> </span></button>
        <a href="<?php echo $link?>" data-ajax="true"><h6><b><?php echo $title?></b></h6></a>
        <a data-ajax="true" class="user-link "  data-id="<?php echo $user['id']?>"  href="<?php echo $C->model('user')->profileUrl($user)?>">
            <?php echo $user['full_name']?>
            <?php echo $C->view('user/badge', array('userid'=> $user['id']))?>
        </a>

    </div>
</div>