<?php $notifications = $C->model('user')->getNotifications()?>

<?php if(count($notifications) > 0):?>
    <?php foreach($notifications as $notification):?>
        <?php echo $C->view('notification/display', array('notification' => $notification))?>
    <?php endforeach?>
<?php else:?>
    <div class="empty-content">
        <i class="la la-bell-slash"></i>
        <span><?php _l('no-notifications')?></span>
    </div>
<?php endif?>
