<div class=" mt-3">
    <?php $radios = model('radio::radio')->getRadios($type,$typeid,0,config('radio-limit', 20))?>
    <?php if(count($radios) > 0):?>
        <div class="main-loadmore-container" data-container="radios-list-container">
            <div
                data-paginate-url="radio/paginate"
                data-param="<?php echo perfectSerialize(array('type' => $type, 'typeId' => $typeid))?>"
                id="radios-list-container"
                class="videos-list-container radios-list-container" data-type="<?php echo $type?>" data-type-id="<?php echo $typeid?>" data-offset="0">

                <?php foreach($radios as $radio):?>
                    <?php echo view('radio::list/display-list', array('radio' => $radio))?>
                <?php endforeach;?>
                <?php if(count($radios) > config('radio-limit', 20) - 1):?>
                    <div class="load-more-button-container" id="radios-list-container-load-more-container">
                        <a href=""
                           data-size="s" data-style="zoom-in"
                           class="load-more-button  btn btn-outline-dark btn-sm ladda-button"
                           data-container="radios-list-container"
                           id="radios-list-container-loadmore-button"><?php _l('load-more')?></a>
                    </div>
                <?php endif?>
            </div>
        </div>
    <?php else:?>
        <div class="empty-content">
            <i class="la la-film"></i>
            <span><?php _l('radio::no-live-stations-display')?></span>

        </div>
    <?php endif?>

</div>