
<?php if($type == 'listen-later'):?>
    <h6 style="color:#A7A59D" class="mb-4"><?php _l('your-tracks-listen-later')?></h6>
<?php elseif($type == 'history'):?>
    <div class="clearfix mb-5">
        <a href="<?php echo url('clear/history')?>" class="btn btn-secondary float-right round-sm ajax-action"><?php _l('clear-history')?></a>
    </div>
<?php endif?>
<div class="track-list" data-view="<?php echo (isset($viewType)) ? $viewType : 'list'?>" data-type-id="<?php echo $typeId?>" data-type="<?php echo $type?>" data-offset="0">
    <?php echo $C->view('track/placeholder')?>
</div>
<a href="" class="track-paginate-link show-mobile-sm show-mobile-md" onclick="return paginateTracks()"><?php _l('load-more-tracks')?></a>
