<form enctype="multipart/form-data" class="general-form" method="post" action="<?php echo getFullUrl(true)?>">
    <?php $user = $C->model('user')->authUser?>
    <div class="form-group mb-5">
        <div class="row">
            <div class="col-sm-4">
                <label class="bold"><?php _l('profile-picture')?></label>
                <span class="form-text text-muted"><?php echo config('image-file-types', 'jpg,png,gif,jpeg')?></span>
            </div>
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-md-3">
                        <div class="input-picker mb-3">
                            <button class="btn btn-outline-secondary btn-sm btn-block"><?php _l('select-image')?></button>
                            <input data-placeholder="#profileAvatar" onchange="validate_file_size(this, 'image')" type="file" name="avatar"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="avatar-placeholder">
                            <div id="profileAvatar" style="background-image: url(<?php echo $C->model('user')->getAvatar(null, 200)?>);display: block;"></div>
                            <i class="la la-photo"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <div class="form-group ">
        <div class="row">
            <div class="col-sm-4">
                <label class="bold"><?php _l('profile-cover')?></label>
                <span class="form-text text-muted"><?php echo config('image-file-types', 'jpg,png,gif,jpeg')?></span>
            </div>
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-md-3">
                        <div class="input-picker mb-3">
                            <button class="btn btn-outline-secondary btn-sm btn-block"><?php _l('select-image')?></button>
                            <input data-placeholder="#profileCover" onchange="validate_file_size(this, 'image')" type="file" name="cover"/>
                        </div>
                    </div>
                    <div class="col">
                        <div class="avatar-placeholder avatar-placeholder-flat">
                            <div id="profileCover" style="background-image: url(<?php echo $C->model('user')->getCover(null)?>);display: block;"></div>
                            <i class="la la-photo"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <hr/>

    <button data-size="s" data-style="zoom-in" class="btn btn-info  ladda-button mt-3" id="account-submit" type="submit"><?php _l('save')?></button>

</form>