<?php
    $theme = config('theme', 'main');
    $color = config($theme.'-colored', '#ff5533');
?>

<div style="position:relative;">

    <form data-upload="#trackUploadProgress" enctype="multipart/form-data" action="<?php echo getFullUrl(true)?>" method="post" class="general-form">
        <?php if(model('user')->isAdmin()):?>
            <input type="hidden" name="val[userid]" value="<?php echo $C->request->input('id')?>"/>
        <?php endif?>
        <div class="inner-container" style="padding-top: 80px;">
            <?php if($page == 'upload'):?>
                <div class="track-selector video-selector pb-4">
                    <i class="fa fa-video-camera"></i>
                    <h5><?php _l('drag-drop-video')?></h5>
                    <span class="mb-4"><?php _l('select-video-note')?> <?php echo model('video::video')->getSupportedTypes()?></span>
                    <input required  onchange="validate_file_size(this, 'video')" class="main-video" type="file" name="video_file"/>
                </div>
            <?php else:?>
                <div class="track-selector video-selector pb-4">
                    <i class="fa fa-video-camera"></i>
                    <h5><?php _l('import-new-video')?></h5>

                    <div  style="width: 60%; margin: auto;">
                        <div class="mb-3">
                            <input id="video-url" autocomplete="off" name="url" type="text" placeholder="<?php _l('enter-video-url')?>" class="form-control input-md mb-1 form-control-active">
                            <span class="help-block"><?php _l('support-video-url')?></span>
                        </div>
                        <button type="button" onclick="return fetchVideo()" class="btn btn-primary round-sm fetch-url"><?php _l('fetch-video')?></button>
                    </div>
                </div>
                <input type="hidden" name="val[video_source]" class="video-source"/>
                <input type="hidden" name="val[video_link]" class="video-link"/>
                <input type="hidden" name="val[video_art]" class="video-art"/>
                <input type="hidden" name="val[duration]" class="video-duration"/>
            <?php endif?>

            <div id="video-form-container" class="hide">
                <div class="row mt-4">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label><?php _l('video-title')?></label>
                            <input type="text" name="val[title]"  class="form-control video-title"/>
                        </div>

                        <div class="form-group">
                            <label><?php _l('video-description')?></label>
                            <textarea name="val[desc]" rows="5" class="form-control video-description"></textarea>
                        </div>



                        <div class="form-group ">
                            <label><?php _l('genre')?></label>
                            <select data-ui-select="true" class=" select-input" name="val[genre]">
                                <?php foreach ($C->model('admin')->getGenres() as $genre):?>
                                    <option value="<?php echo $genre['id']?>"><?php echo $genre['name']?></option>
                                <?php endforeach;?>
                            </select>
                        </div>

                        <?php if($page == 'upload' and model('video::video')->canSell()):?>
                            <div class="form-group">
                                <label><?php _l('price')?></label>
                                <input step="0.01" type="number" autocomplete="off"  name="val[price]" class=" form-control" >
                            </div>
                        <?php endif?>

                        <div class="form-group">
                            <label><?php _l('tags')?></label>
                            <input autocomplete="off" type="text" name="val[tags]" class=" input-tags video-tags" >
                        </div>

                        <div class="form-group">
                            <label><?php _l('link-to-your-track')?></label>
                            <select name="val[track_id]"  data-url="track/track-tags" class="trackinput input-tags-fetch">
                            </select>
                        </div>

                        <div class="form-group">
                            <label><?php _l('privacy')?></label>
                            <select name="val[privacy]" class="form-control">
                                <option value="1"><?php _l('public')?></option>
                                <option value="2"><?php _l('private')?></option>
                            </select>
                        </div>


                    </div>
                    <div class="col-md-4">
                        <div class="avatar-placeholder mt-4" style="width: 100%;height:170px;border-style:dashed">
                            <div id="songAvatar"></div>
                            <i class="la la-photo"></i>
                        </div>

                        <div class="input-picker mb-3">
                            <button class="btn btn-secondary btn-sm btn-block round-sm"><?php _l('select-image')?></button>
                            <input id="songAvatar-input" <?php echo ($page == 'upload' and model('video::video')->getSupportedTypes() == 'mp4') ? 'required' : null?> data-placeholder="#songAvatar" onchange="validate_file_size(this, 'image')" type="file" name="img"/>
                        </div>


                        <div class="form-group row">
                            <label for="staticEmail" class="col-sm-6 col-form-label"><?php _l('enable-comments')?></label>
                            <div class="col-sm-6">
                                <input type="hidden" name="val[comments]" value="0"/>
                                <div class="switch">
                                    <input id="cmn-toggle-comments" value="1" name="val[comments]"  checked class="cmn-toggle cmn-toggle-round-flat" type="checkbox">
                                    <label for="cmn-toggle-comments"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <hr/>
                <div class="progress mt-1 hide" id="trackUploadProgress" style="margin: 7px 0; height:2px;">
                    <div class="progress-bar" role="progressbar" style="width: 0%;background:#FF533E;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <button data-size="s" data-style="zoom-in" id="upload-submit" class="btn btn-primary round-sm ladda-button" type="submit"><?php _l('publish')?></button>
            </div>

        </div>


    </form>
</div>