
<div class="text-center pb-4">
    <a data-ajax="true" href="<?php echo url('store/dashboard', array('w' => 'track'))?>"  class="btn btn-sm <?php echo $page == 'track' ? 'btn-primary' : 'btn-secondary'?>">
        <?php _l('tracks')?>
    </a>
    <?php if(moduleExists('video') and model('video::video')->canSell()):?>
        <a data-ajax="true" href="<?php echo url('store/dashboard', array('w' => 'video'))?>"  class="btn btn-sm <?php echo $page == 'video' ? 'btn-primary' : 'btn-secondary'?>">
            <?php _l('videos')?>
        </a>
    <?php endif?>
    <a data-ajax="true" href="<?php echo url('store/dashboard', array('w' => 'album'))?>"  class="btn btn-sm <?php echo $page == 'album'? 'btn-primary' : 'btn-secondary'?>">
        <?php _l('albums')?>
    </a>

    <?php if(moduleExists('video') and model('video::video')->canSell()):?>

    <?php endif?>
</div>

<table class="table table-responsive-sm">
    <thead class="thead-light">
    <tr>
        <th scope="col" style="width: 10%">#</th>
        <th scope="col"  style="width: 10%"><?php _l('by')?></th>
        <th scope="col"  style="width: 35%"><?php _l('song-name')?></th>
        <th scope="col"  style="width: 15%"><?php _l('date')?></th>
        <th scope="col"  style="width: 10%"><?php _l('total-amount')?></th>
        <th scope="col"  style="width: 10%"><?php _l('profit')?></th>
        <th scope="col"  style="width: 10%"><?php _l('status')?></th>
    </tr>
    </thead>
    <tbody>
    <?php $transactions = model('store::store')->getTransactions($page)?>
    <?php foreach($transactions->results() as $transaction): $user = model('user')->getUser($transaction['userid'])?>
        <tr>
            <td><?php echo $transaction['id']?></td>
            <td>
                <a href="<?php echo model('user')->profileUrl($user)?>" data-ajax="true"><strong><?php echo $user['username']?></strong></a>
            </td>
            <td>
                <?php if($page == 'track'):?>
                    <?php $track = model('track')->findTrack($transaction['type_id']);?>
                    <a data-ajax="true" href="<?php echo model('track')->trackUrl($track)?>"><?php echo $track['title']?></a>
                <?php elseif($page == 'video'):?>
                    <?php $video = model('video::video')->find($transaction['type_id']);?>
                    <a data-ajax="true" href="<?php echo model('video::video')->videoUrl($video)?>"><?php echo $video['title']?></a>
                <?php else:?>
                    <?php $playlist = model('track')->findPlaylist($transaction['type_id']);?>
                    <a data-ajax="true" href="<?php echo model('track')->playlistUrl($playlist)?>"><?php echo $playlist['name']?></a>
                <?php endif?>

            </td>
            <td>
                <?php echo date('m - d - Y', $transaction['time'])?>
            </td>
            <td>
                <?php echo formatMoney($transaction['amount'])?>
            </td>
            <td>
                <?php echo formatMoney($transaction['amount_credited'])?>
            </td>
            <td>
                <?php if($transaction['status'] == 3):?>
                    <span class="badge"><?php _l('pending')?></span>
                <?php else:?>
                    <span class="badge <?php echo ($transaction['status']) ? 'badge-success' : 'badge-danger'?>"><?php echo ($transaction['status']) ? l('successful') : l('failed')?></span>
                <?php endif?>
            </td>
        </tr>
    <?php endforeach?>
    </tbody>
</table>
<?php if($transactions->total < 1):?>
    <div class="empty-content" style="padding:5% 0">
        <i class="la la-money"></i>
        <span><?php _l('no-contents-show')?></span>
    </div>
<?php else:?>
    <?php echo $transactions->links()?>
<?php endif?>