<?php $user = model('user')->getUser(); if($user['stripe_customer_id']):?>
    <div class="alert alert-info">
        <div class="row mt-1">
            <div class="col-sm-6">
                <?php _l('cancel-subscription')?>
            </div>
            <div class="col-sm-6">
                <a href="<?php echo url('payment/stripe/cancel')?>" class="btn btn-sm btn-danger round-sm confirm" data-message="<?php _l('are-sure-cancel-sub')?>" data-ajax-action="true"><?php _l('cancel-subscription')?></a>
            </div>
        </div>
    </div>
<?php endif?>
<table class="table table-responsive-sm">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col"><?php _l('pro-plan')?></th>
        <th scope="col"><?php _l('status')?></th>
        <th scope="col"><?php _l('valid-till')?></th>
        <th scope="col"><?php _l('paid-on')?></th>
    </tr>
    </thead>
    <tbody>
    <?php $transaction = (model('user')->authUser['user_type'] == 1) ? $C->model('admin')->getLastTransaction($C->model('user')->authId, 'pro-users') : $C->model('admin')->getLastTransaction($C->model('user')->authId, 'pro')?>
    <tr>
        <th scope="row">1</th>
        <td><strong><?php _l('pro')?> (<?php _l($transaction['type_id'])?>)</strong></td>
        <td><?php echo ($transaction['status'] == 1 and $transaction['valid_time'] > time()) ? l('active') : l('inactive')?></td>
        <td><?php echo date('d/m/y', $transaction['valid_time'])?></td>
        <td><?php echo date('d/m/y', $transaction['time'])?></td>
    </tr>

    </tbody>
</table>