<form class="general-form" method="post" action="<?php echo getFullUrl(true)?>">
    <?php $user = $C->model('user')->authUser?>


    <div class="form-group mb-5">
        <div class="row">
            <div class="col-sm-4">
                <label class="bold"><?php _l('current-password')?></label>
                <span class="form-text text-muted"><?php _l('enter-current-password')?></span>
            </div>
            <div class="col-sm-8">
                <input required type="password" class="form-control" name="val[current]" value=""/>
            </div>
        </div>

    </div>

    <hr/>

    <div class="form-group mb-5">
        <div class="row">
            <div class="col-sm-4">
                <label class="bold"><?php _l('choose-password')?></label>
                <span class="form-text text-muted"><?php _l('enter-new-password')?></span>
            </div>
            <div class="col-sm-8">
                <input required type="password" class="form-control" name="val[new]" value=""/>
            </div>
        </div>

    </div>

    <div class="form-group mb-5">
        <div class="row">
            <div class="col-sm-4">
                <label class="bold"><?php _l('confirm-password')?></label>
                <span class="form-text text-muted"><?php _l('repeat-new-password')?></span>
            </div>
            <div class="col-sm-8">
                <input required type="password" class="form-control" name="val[confirm]" value=""/>
            </div>
        </div>

    </div>

    <hr/>

    <button data-size="s" data-style="zoom-in" class="btn btn-info  ladda-button mt-3" id="account-submit" type="submit"><?php _l('save')?></button>

</form>