<div class="getstarted-header">
    <div class="inner-container">
        <div class="clearfix">
            <div class="float-left">
                <a href="#" class="btn disabled" id="getstarted-back" ><?php _l('reset-password')?></a>
            </div>


        </div>
    </div>
</div>

<div class="inner-container" style="margin-bottom: 100px">
    <div class="row mt-5">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h6><?php _l('choose-new-password')?></h6>

            <form action="" class="general-form" method="post">


                <div class="form-group mt-4">
                    <input name="val[password]" type="password" class="form-control " placeholder="<?php _l('new-password')?>"/>
                </div>

                <div class="form-group mt-4 mb-3">
                    <input name="val[password2]" type="password" class="form-control " placeholder="<?php _l('confirm-password')?>"/>
                </div>

                <button type="submit" data-style="zoom-in" data-size="s" class="btn  btn-primary ladda-button" id="forgot-submit"><?php _l('reset-password')?></button>
            </form>
        </div>
    </div>
</div>