

<div class="account-card">
    <div class="clearfix">
        <div class="float-right">
            <a data-ajax="true" style="font-size: 15px;color: #ffffff;" href="<?php echo url('settings')?>"><i class="la la-cog"></i></a>
        </div>
    </div>
    <div class=" mt-4 mb-4">
        <a data-ajax="true" class="mt-1" href="<?php echo $C->model('user')->profileUrl()?>">
            <img style="width:35px;height: 35px;-webkit-border-radius: 100px;-moz-border-radius: 100px;border-radius: 100px;border: solid 2px white;" src="<?php echo $C->model('user')->getAvatar()?>"/>
        </a>
        <h6 class="mt-3 mb-0" style="font-size: 15px;font-weight: 600;color: #ffffff;"><a style="color: #ffffff;" data-ajax="true" href="<?php echo $C->model('user')->profileUrl()?>"><?php echo $C->model('user')->authUser['full_name']?></a></h6>

    </div>

    <?php $value = $C->model('user')->getCompleteness()?>
    <?php if($value < 100):?>
        <div class="progress" style="height: 6px;">
            <div class="progress-bar progress-bar-striped progress-bar-animated " role="progressbar" style="width: <?php echo $value?>%;background: #FD6F6C;" aria-valuenow="<?php echo $value?>" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

        <div class="completion">

            <div class="clearfix">
                <div class="float-left">
                    <h6 style="font-size: 13px" class="mb-0"><?php _l('your-profile-is')?></h6>
                    <div class="mt-3"><?php echo $value?>% <?php _l('complete')?></div>
                </div>

            </div>
        </div>
    <?php endif?>


</div>