<div class="inner-container">
    <form   action="<?php echo getFullUrl(true)?>" class="general-form mb-5" method="post">
        <div class="upload-types">
            <h4><?php _l('contact-us')?></h4>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="each" style="text-align: left;height:auto;padding:40px;cursor: default">
                        <div class="form-group">
                            <label><?php _l('first-name')?></label>

                            <input type="text" name="val[first_name]" class="form-control"/>
                        </div>

                        <div class="form-group">
                            <label><?php _l('last-name')?></label>

                            <input type="text" name="val[last_name]" class="form-control"/>
                        </div>

                        <div class="form-group">
                            <label><?php _l('email-address')?></label>

                            <input type="text" name="val[email]" class="form-control"/>
                        </div>

                        <div class="form-group">
                            <label><?php _l('message')?></label>

                            <textarea name="val[message]" class="form-control" rows="5"></textarea>
                        </div>

                        <button type="submit" data-size="s" data-style="zoom-in" class="btn btn-primary btn-sm ladda-button" id="contact-button"><?php _l('send-message')?></button>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </form>
</div>