<div class="inner-container">
    <div class="row mt-4">
        <div class="col-md-7">
            <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form">
                <div class="form-group row">
                    <label for="inputPassword" class="col-sm-2 col-form-label"><?php _l('ad-unit1')?></label>
                    <div class="col-sm-10">
                        <textarea name="val[ad-unit1]" class="form-control" rows="5"><?php echo config('ad-unit1')?></textarea>
                        <span class="text-muted"><?php _l('ad-unit1-note')?></span>
                    </div>
                </div>
                <hr/>
                <div class="form-group row">
                    <label for="inputPassword" class="col-sm-2 col-form-label"><?php _l('ad-unit2')?></label>
                    <div class="col-sm-10">
                        <textarea name="val[ad-unit2]" class="form-control" rows="5"><?php echo config('ad-unit2')?></textarea>
                        <span class="text-muted"><?php _l('ad-unit2-note')?></span>
                    </div>
                </div>

                
                <hr/>
                <button data-size="s" data-style="zoom-in" class="btn btn-primary round-sm ladda-button" id="ads-button"><?php _l('save-changes')?></button>
            </form>
        </div>
    </div>
</div>