<div class="inner-container mt-4">
    <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form">
        <div class="form-group">
            <label><?php _l('page-title')?></label>
            <input type="text" name="val[title]" class="form-control"/>
            <span class="text-muted"><?php _l('page-title-note')?></span>
        </div>

        <div class="form-group">
            <label><?php _l('page-url')?></label>
            <input type="text" name="val[url]" class="form-control"/>
            <span class="text-muted"><?php _l('page-url-note')?></span>
        </div>

        <div class="form-group">
            <label><?php _l('page-content')?></label>
            <textarea  name="val[content]" class="form-control rich-editor" id="newpage"  rows="6"></textarea>
            <span class="text-muted"><?php _l('page-content-note')?></span>
        </div>

        <div class="form-group row">
            <label class="col-sm-4"><?php _l('menu-location')?></label>
            <select class="col-sm-4 form-control" name="val[location]">
                <option value="footer"><?php _l('footer-menu')?></option>
                <option value="side"><?php _l('side-menu')?></option>
            </select>
        </div>

        <button data-size="s" data-style="zoom-in" class="btn btn-primary round-sm ladda-button" id="pages-button"><?php _l('save-changes')?></button>
    </form>
</div>